#! /bin/bash

# Need to pytest before commit via `uv`
echo "Running tests before commit..."

# Check the files what located at `src` was changed
CHANGED=$(git diff --cached --name-only --diff-filter=ACM | grep '^src/')
if [ -z "$CHANGED" ]; then
    echo "No changes in 'src/' directory. Skipping tests."
    exit 0
fi

# Run tests using `uv`
if ! uv run pytest -q; then
    echo "Tests failed. Commit aborted."
    exit 1
fi

echo "All tests passed. Proceeding with commit."
exit 0